buildingcodes:
  - "BLD1"
  - "BLD2"
  - "BLD3"
  - "BLD5"
  - "BLD6"
tugs:
  - "agv1"
  - "agv2"
  - "agv3"
right_side_sensors:
  - 0
  - 2
left_side_sensors:
  - 1
  - 3
calibration_map:
  0: -1
  1: -1
  2: -1
  3: -1
door_list:
  - "Dock-inner"
  - "Middle"
  - "Dock-outer"
  - "Hallway"
  - "MDF-in"
  - "DH-in"
  - "DH-return"
  - "MDF-return"
  - "Hallway-return"
  - "Dock-outer-return"
  - "middle-return"
  - "Dock-inner-return"
